### ISSUE TITLE
Escrever personas da especificação do projeto

### ISSUE THREAD

**Issue by Tleds** [ProfKleberSouza/projeto-pratico-dad-grupo-3#2]

**Comment by rafaelsiq** [comment]
Conteúdo escrito no arquivo a seguir:
https://docs.google.com/document/d/1weJaV0R7To_xsyVjhgBrx5RjxzbS2CoBwjVpfNfr3gU/edit
Pode ser localizado na seção do titulo Especificação do projeto, subtítulo Persona
